FROM node:20

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml .
RUN pnpm i

COPY . .

ARG NEXT_PUBLIC_API
ARG NEXT_PUBLIC_NATS_SERVER
ARG NEXT_PUBLIC_NATS_JWT_TOKEN
ARG NEXT_PUBLIC_NATS_NKEY
ARG NEXT_PUBLIC_SOLANA_EXPLORER

ENV NEXT_PUBLIC_API=${NEXT_PUBLIC_API}
ENV NEXT_PUBLIC_NATS_SERVER=${NEXT_PUBLIC_NATS_SERVER}
ENV NEXT_PUBLIC_NATS_JWT_TOKEN=${NEXT_PUBLIC_NATS_JWT_TOKEN}
ENV NEXT_PUBLIC_NATS_NKEY=${NEXT_PUBLIC_NATS_NKEY}
ENV NEXT_PUBLIC_SOLANA_EXPLORER=${NEXT_PUBLIC_SOLANA_EXPLORER}

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]
